on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: 
      name: DEV
      url: https://github.com
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"

      - name: Install dependencies
        run: npm install

      - name: Create Build
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 950e467f84364c1289bde32f0c5fbbd2
          projectName: er-waittimes-feed
          directory: build
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: main
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: '3'